# Generated by Django 5.2.17 on 2026-08-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routing_api", "0002_modeldeployment_uq_deployment_current"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="modeldeployment",
            name="ck_deployment_activation_order",
        ),
        migrations.AlterField(
            model_name="modeldeployment",
            name="deployment_state",
            field=models.CharField(
                choices=[
                    ("REGISTERED", "REGISTERED"),
                    ("VALIDATED", "VALIDATED"),
                    ("SHADOW", "SHADOW"),
                    ("CANARY", "CANARY"),
                    ("ACTIVE", "ACTIVE"),
                    ("RETIRED", "RETIRED"),
                    ("REJECTED", "REJECTED"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("REGISTERED", "REGISTERED"),
                    ("VALIDATED", "VALIDATED"),
                    ("SHADOW", "SHADOW"),
                    ("CANARY", "CANARY"),
                    ("ACTIVE", "ACTIVE"),
                    ("RETIRED", "RETIRED"),
                    ("REJECTED", "REJECTED"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="modeldeployment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("deployment_state__in", ("SHADOW", "CANARY", "ACTIVE", "RETIRED"))
                ),
                name="ck_deployment_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="modeldeployment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("deployment_state", "RETIRED"), _negated=True),
                    ("deactivated_at__isnull", False),
                    _connector="OR",
                ),
                name="ck_retired_deactivated",
            ),
        ),
        migrations.AddConstraint(
            model_name="modeldeployment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("deployment_state", "SHADOW"), ("traffic_fraction", 0)),
                    models.Q(
                        ("deployment_state", "CANARY"),
                        ("traffic_fraction__gt", 0),
                        ("traffic_fraction__lt", 1),
                    ),
                    models.Q(("deployment_state", "ACTIVE"), ("traffic_fraction", 1)),
                    ("deployment_state", "RETIRED"),
                    _connector="OR",
                ),
                name="ck_deployment_state_traffic",
            ),
        ),
        migrations.AddConstraint(
            model_name="modeldeployment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("deactivated_at__isnull", True),
                    models.Q(
                        ("activated_at__isnull", False),
                        ("deactivated_at__gte", models.F("activated_at")),
                    ),
                    _connector="OR",
                ),
                name="ck_deployment_activation_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="modelversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        (
                            "REGISTERED",
                            "VALIDATED",
                            "SHADOW",
                            "CANARY",
                            "ACTIVE",
                            "RETIRED",
                            "REJECTED",
                        ),
                    )
                ),
                name="ck_model_version_state",
            ),
        ),
    ]
