"""Framework-independent, deterministic multimodal routing domain."""

from .candidate_generation import (
    BoundedCandidateGenerator,
    CandidateBatch,
    OptimalityUncertifiedError,
)
from .evaluation import CandidateEvaluator, CandidateEvaluationError
from .evaluators import StaticLegEvaluator, TimeBand, TimeBandLegEvaluator
from .graph_search import (
    CanonicalRoutingGraph,
    GraphPathRejection,
    GraphSearchCaps,
    GraphSearchResult,
    GraphSearchUncertifiedError,
    TimeDependentGraphSearch,
)
from .models import (
    BusWaitContribution,
    CandidateSeed,
    EvaluatedCandidate,
    EvaluatedLeg,
    LegCost,
    LegSpec,
    MoneyRange,
    OptimizationResult,
    RecommendationSet,
    RouteConstraints,
    TimeEstimate,
    TransferRequirement,
)
from .optimizer import GraphOptimizationOutcome, RouteOptimizer
from .policy import CandidateCaps, EpsilonPolicy, RankingPolicy
from .search import (
    SearchCertificate,
    SearchNotCertifiedError,
    SearchObjective,
    SearchOutcome,
    SearchProtocolError,
    TimeDependentCandidateSearch,
)
from .strategy_generation import (
    AccessHub,
    BoundedStrategyGenerator,
    CandidateExactificationPlan,
    CanonicalTransitTopology,
    EgressHub,
    EnrichmentKind,
    EntryTimeBasis,
    ExactEnrichmentRequest,
    ExactificationPlan,
    ExactificationStep,
    ExactQuoteIdentity,
    QuoteReadiness,
    StrategyCandidate,
    StrategyExactificationBatch,
    StrategyGenerationBatch,
    StrategyGenerationInput,
    StrategyGenerationPolicy,
    StrategyRejection,
    StrategySearchFrontier,
    StrategySearchSpace,
    TaxiBridge,
    TaxiQuote,
    TransitBaseline,
    TransitLegInput,
    UpstreamHub,
    WalkQuote,
)

__all__ = [
    "BoundedCandidateGenerator",
    "BoundedStrategyGenerator",
    "BusWaitContribution",
    "CandidateBatch",
    "CandidateCaps",
    "CandidateEvaluationError",
    "CandidateEvaluator",
    "CandidateExactificationPlan",
    "CandidateSeed",
    "CanonicalRoutingGraph",
    "CanonicalTransitTopology",
    "AccessHub",
    "EgressHub",
    "EnrichmentKind",
    "EntryTimeBasis",
    "ExactEnrichmentRequest",
    "ExactificationPlan",
    "ExactificationStep",
    "ExactQuoteIdentity",
    "EpsilonPolicy",
    "EvaluatedCandidate",
    "EvaluatedLeg",
    "LegCost",
    "LegSpec",
    "GraphPathRejection",
    "GraphSearchCaps",
    "GraphSearchResult",
    "GraphSearchUncertifiedError",
    "GraphOptimizationOutcome",
    "MoneyRange",
    "OptimizationResult",
    "OptimalityUncertifiedError",
    "RankingPolicy",
    "QuoteReadiness",
    "RecommendationSet",
    "RouteConstraints",
    "RouteOptimizer",
    "SearchCertificate",
    "SearchNotCertifiedError",
    "SearchObjective",
    "SearchOutcome",
    "SearchProtocolError",
    "StaticLegEvaluator",
    "StrategyCandidate",
    "StrategyExactificationBatch",
    "StrategyGenerationBatch",
    "StrategyGenerationInput",
    "StrategyGenerationPolicy",
    "StrategyRejection",
    "StrategySearchFrontier",
    "StrategySearchSpace",
    "TaxiBridge",
    "TaxiQuote",
    "TimeBand",
    "TimeBandLegEvaluator",
    "TimeDependentCandidateSearch",
    "TimeDependentGraphSearch",
    "TimeEstimate",
    "TransitBaseline",
    "TransitLegInput",
    "TransferRequirement",
    "UpstreamHub",
    "WalkQuote",
]
