"""Framework-independent, deterministic multimodal routing domain."""

from .candidate_generation import BoundedCandidateGenerator, CandidateBatch
from .evaluation import CandidateEvaluator, CandidateEvaluationError
from .evaluators import StaticLegEvaluator, TimeBand, TimeBandLegEvaluator
from .models import (
    BusWaitContribution,
    CandidateSeed,
    EvaluatedCandidate,
    EvaluatedLeg,
    LegCost,
    LegSpec,
    MoneyRange,
    OptimizationResult,
    RecommendationSet,
    RouteConstraints,
    TimeEstimate,
    TransferRequirement,
)
from .optimizer import RouteOptimizer
from .policy import CandidateCaps, EpsilonPolicy, RankingPolicy
from .strategy_generation import (
    AccessHub,
    BoundedStrategyGenerator,
    CandidateExactificationPlan,
    CanonicalTransitTopology,
    EgressHub,
    EnrichmentKind,
    EntryTimeBasis,
    ExactEnrichmentRequest,
    ExactificationPlan,
    ExactificationStep,
    ExactQuoteIdentity,
    QuoteReadiness,
    StrategyCandidate,
    StrategyGenerationBatch,
    StrategyGenerationInput,
    StrategyGenerationPolicy,
    StrategyRejection,
    TaxiBridge,
    TaxiQuote,
    TransitBaseline,
    TransitLegInput,
    UpstreamHub,
    WalkQuote,
)

__all__ = [
    "BoundedCandidateGenerator",
    "BoundedStrategyGenerator",
    "BusWaitContribution",
    "CandidateBatch",
    "CandidateCaps",
    "CandidateEvaluationError",
    "CandidateEvaluator",
    "CandidateExactificationPlan",
    "CandidateSeed",
    "CanonicalTransitTopology",
    "AccessHub",
    "EgressHub",
    "EnrichmentKind",
    "EntryTimeBasis",
    "ExactEnrichmentRequest",
    "ExactificationPlan",
    "ExactificationStep",
    "ExactQuoteIdentity",
    "EpsilonPolicy",
    "EvaluatedCandidate",
    "EvaluatedLeg",
    "LegCost",
    "LegSpec",
    "MoneyRange",
    "OptimizationResult",
    "RankingPolicy",
    "QuoteReadiness",
    "RecommendationSet",
    "RouteConstraints",
    "RouteOptimizer",
    "StaticLegEvaluator",
    "StrategyCandidate",
    "StrategyGenerationBatch",
    "StrategyGenerationInput",
    "StrategyGenerationPolicy",
    "StrategyRejection",
    "TaxiBridge",
    "TaxiQuote",
    "TimeBand",
    "TimeBandLegEvaluator",
    "TimeEstimate",
    "TransitBaseline",
    "TransitLegInput",
    "TransferRequirement",
    "UpstreamHub",
    "WalkQuote",
]
